tasks: industry -> occupation -> occupation_income -> industry_income -> travel_to_work -> work_hours
cfg:
  industry:
    targets:
      - industry
      - work_status
    features:
      - age
      - gender
      - location
  occupation:
    targets:
      - occupation
    features:
      - age
      - gender
      - location
      - industry
  occupation_income:
    targets:
      - income
    features:
      - age
      - gender
      - location
      - occupation
  industry_income:
    targets:
      - income
    features:
      - age
      - gender
      - location
      - industry
  travel_to_work:
    targets:
      - travel_to_work
    features:
      - age
      - gender
      - location
  work_hours:
    targets:
      - work_hours
    features:
      - age
      - gender
      - occupation
